### ISSUE TITLE
Build error against PostgreSQL 15

### ISSUE THREAD

**Issue by devrimgunduz** [pgexporter/pgexporter_ext#8]
Hi @jesperpedersen ,

0.2.0 fails to build against PostgreSQL 15. Can you please take a look?

Thanks!

`[ 66%] Building C object src/CMakeFiles/pgexporter_ext.dir/pgexporter_ext/utils.c.o
[ 66%] Building C object src/CMakeFiles/pgexporter_ext.dir/pgexporter_ext/lib.c.o
/var/lib/pgsql/git/pgrpms/rpm/redhat/main/non-common/pgexporter_ext/main/pgexporter_ext-0.2.0/src/pgexporter_ext/lib.c: In function 'network_info':
/var/lib/pgsql/git/pgrpms/rpm/redhat/main/non-common/pgexporter_ext/main/pgexporter_ext-0.2.0/src/pgexporter_ext/lib.c:935:14: warning: implicit declaration of function 'getnameinfo' [-Wimplicit-function-declaration]
  935 |          if (getnameinfo(ifa->ifa_addr, sizeof(struct sockaddr_in), host, MAXPGPATH, NULL, 0, NI_NUMERICHOST) != 0)
      |              ^~~~~~~~~~~
/var/lib/pgsql/git/pgrpms/rpm/redhat/main/non-common/pgexporter_ext/main/pgexporter_ext-0.2.0/src/pgexporter_ext/lib.c:935:48: error: invalid application of 'sizeof' to incomplete type 'struct sockaddr_in'
  935 |          if (getnameinfo(ifa->ifa_addr, sizeof(struct sockaddr_in), host, MAXPGPATH, NULL, 0, NI_NUMERICHOST) != 0)
      |                                                ^~~~~~
/var/lib/pgsql/git/pgrpms/rpm/redhat/main/non-common/pgexporter_ext/main/pgexporter_ext-0.2.0/src/pgexporter_ext/lib.c:935:95: error: 'NI_NUMERICHOST' undeclared (first use in this function)
  935 |          if (getnameinfo(ifa->ifa_addr, sizeof(struct sockaddr_in), host, MAXPGPATH, NULL, 0, NI_NUMERICHOST) != 0)
      |                                                                                               ^~~~~~~~~~~~~~
/var/lib/pgsql/git/pgrpms/rpm/redhat/main/non-common/pgexporter_ext/main/pgexporter_ext-0.2.0/src/pgexporter_ext/lib.c:935:95: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [src/CMakeFiles/pgexporter_ext.dir/build.make:76: src/CMakeFiles/pgexporter_ext.dir/pgexporter_ext/lib.c.o] Error 1
`

**Comment by jesperpedersen** [comment]
The definitions moved to `server/getaddrinfo.h`, so we need a `CHECK_INCLUDE_FILE` solution - e.g. `HAVE_GETADDRINFO.H`

@resyfer - Feel free to pick this up as well

**Comment by resyfer** [comment]
@jesperpedersen After having looked at the error, I feel its mainly due to it not being able find `getnameinfo`, and some related macros, all of which are found in the `netdb.h` header file.

So inserting a `#include <netdb.h>` at Line 39 in `lib.c` would work for C17 on Linux. Seems to work for me.

**Comment by jesperpedersen** [comment]
@resyfer Remember to add yourself to the `AUTHORS` file...

**Comment by jesperpedersen** [comment]
@devrimgunduz https://github.com/pgexporter/pgexporter_ext/releases/tag/0.2.1

**Comment by jesperpedersen** [comment]
@devrimgunduz https://github.com/pgexporter/pgexporter_ext/releases/tag/0.2.2

**Comment by devrimgunduz** [comment]
@jesperpedersen @resyfer thanks a lot!
